"""
push_vouchers.py
─────────────────────────────────────────────────────────────────────────────
Reads vouchers_to_create.csv (generated by generate_from_frontend.js)
and pushes ALL vouchers to Tally Prime (Wallnut3) in batches.

New narration format stored in Tally:
  Item: <name> | Qty: N UOM | Rate: R | Area: A | SO: S | State: ST

This matches exactly what tallyFetchService.parseLiveSalesFromTally() expects.

Usage:
  python push_vouchers.py            # push new vouchers only (uses pushed_log.json)
  python push_vouchers.py --reset    # wipe log and push everything fresh
"""

import requests
import xml.etree.ElementTree as ET
import csv
import json
import os
import sys

TALLY_URL    = "http://localhost:9000"
COMPANY_NAME = "Wallnut3"
BATCH_SIZE   = 50

def escape_xml(val):
    return str(val)\
        .replace("&", "&amp;")\
        .replace("<", "&lt;")\
        .replace(">", "&gt;")\
        .replace('"', "&quot;")\
        .replace("'", "&apos;")

def post_xml(xml_body):
    try:
        response = requests.post(
            TALLY_URL,
            data=xml_body.encode('utf-8'),
            headers={'Content-Type': 'text/xml;charset=UTF-8'},
            timeout=30
        )
        return response.text
    except Exception as e:
        return f"<ERRORS>{e}</ERRORS>"

def log_batch_result(batch_idx, response_text):
    try:
        root = ET.fromstring(response_text)
        created    = root.findtext(".//CREATED")    or "0"
        errors     = root.findtext(".//ERRORS")     or "0"
        exceptions = root.findtext(".//EXCEPTIONS") or "0"
        line_errors = [e.text for e in root.findall(".//LINEERROR") if e.text]

        print(f"  Batch {batch_idx+1}: created={created}, errors={errors}, exceptions={exceptions}")
        if line_errors:
            for le in line_errors[:5]:  # show first 5
                print(f"    LINEERROR: {le}")

        return int(errors) == 0 and int(exceptions) == 0 and len(line_errors) == 0
    except Exception as e:
        print(f"  Failed to parse response: {e}")
        print(f"  Raw response (first 500 chars): {response_text[:500]}")
        return False

def build_envelope(vouchers_xml, id_tag="Vouchers"):
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<ENVELOPE>
 <HEADER>
  <TALLYREQUEST>Import Data</TALLYREQUEST>
 </HEADER>
 <BODY>
  <IMPORTDATA>
   <REQUESTDESC>
    <REPORTNAME>Vouchers</REPORTNAME>
    <STATICVARIABLES>
     <SVCURRENTCOMPANY>{escape_xml(COMPANY_NAME)}</SVCURRENTCOMPANY>
    </STATICVARIABLES>
   </REQUESTDESC>
   <REQUESTDATA>
    {vouchers_xml}
   </REQUESTDATA>
  </IMPORTDATA>
 </BODY>
</ENVELOPE>"""

def build_voucher_xml(v, vid):
    """
    Build a single TALLYMESSAGE block for one voucher row.
    v is a dict from csv.DictReader with keys:
      Date, VchNo, VchType, Dealer, Product, Qty, Rate, Amount, UOM,
      SalesOfficer, Area, State
    """
    vch_type    = v.get('VchType', 'Sales').strip()
    is_credit   = 'credit' in vch_type.lower()
    tally_type  = 'Credit Note' if is_credit else 'Sales'
    sales_ledger = 'Sales Returns' if is_credit else 'Sales Accounts'

    qty    = int(float(v.get('Qty', 0) or 0))
    rate   = float(v.get('Rate', 0) or 0)
    amount = int(float(v.get('Amount', 0) or 0)) or (qty * int(rate))
    uom    = escape_xml(v.get('UOM', '').strip())
    dealer = escape_xml(v.get('Dealer', '').strip())
    product = escape_xml(v.get('Product', '').strip())
    so     = escape_xml(v.get('SalesOfficer', '').strip())
    area   = escape_xml(v.get('Area', '').strip())
    state  = escape_xml(v.get('State', '').strip())
    date   = v.get('Date', '').strip().replace('-', '')

    # Amount sign rules (same as xmlGenerator.js)
    # Sales:       party Dr (-amount), sales Cr (+amount)
    # Credit Note: party Cr (+amount), sales Dr (-amount)
    if is_credit:
        party_amount = amount     # credit note: party gets refund (positive = credit)
        sales_amount = -amount
    else:
        party_amount = -amount    # normal sale: party owes us (negative = debit)
        sales_amount = amount

    party_deemed = "Yes"  # party always debit in sales
    sales_deemed = "No"   # sales/income always credit

    # Narration: full structured format for dashboard to parse back
    narration = f"Item: {product} | Qty: {qty} {uom} | Rate: {int(rate)} | Area: {area} | SO: {so} | State: {state}"

    return f"""
    <TALLYMESSAGE xmlns:UDF="TallyUDF">
     <VOUCHER VCHTYPE="{tally_type}" ACTION="CREATE">
      <DATE>{date}</DATE>
      <EFFECTIVEDATE>{date}</EFFECTIVEDATE>
      <ISOPTIONAL>No</ISOPTIONAL>
      <PERSISTEDVIEW>Accounting Voucher View</PERSISTEDVIEW>
      <VOUCHERTYPENAME>{tally_type}</VOUCHERTYPENAME>
      <VOUCHERNUMBER>{escape_xml(vid)}</VOUCHERNUMBER>
      <PARTYLEDGERNAME>{dealer}</PARTYLEDGERNAME>
      <NARRATION>{narration}</NARRATION>
      <ALLLEDGERENTRIES.LIST>
       <LEDGERNAME>{dealer}</LEDGERNAME>
       <ISDEEMEDPOSITIVE>{party_deemed}</ISDEEMEDPOSITIVE>
       <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
       <AMOUNT>{party_amount}</AMOUNT>
      </ALLLEDGERENTRIES.LIST>
      <ALLLEDGERENTRIES.LIST>
       <LEDGERNAME>{sales_ledger}</LEDGERNAME>
       <ISDEEMEDPOSITIVE>{sales_deemed}</ISDEEMEDPOSITIVE>
       <AMOUNT>{sales_amount}</AMOUNT>
      </ALLLEDGERENTRIES.LIST>
      <ALLINVENTORYENTRIES.LIST>
       <STOCKITEMNAME>{product}</STOCKITEMNAME>
       <ISDEEMEDPOSITIVE>{"Yes" if is_credit else "No"}</ISDEEMEDPOSITIVE>
       <RATE>{int(rate)}/{uom}</RATE>
       <AMOUNT>{-amount if not is_credit else amount}</AMOUNT>
       <ACTUALQTY>{qty} {uom}</ACTUALQTY>
       <BILLEDQTY>{qty} {uom}</BILLEDQTY>
      </ALLINVENTORYENTRIES.LIST>
     </VOUCHER>
    </TALLYMESSAGE>"""

def run():
    # -- Reset flag ------------------------------------------------------------
    reset = '--reset' in sys.argv
    log_file = os.path.join(os.path.dirname(__file__), 'pushed_log.json')

    if reset and os.path.exists(log_file):
        os.remove(log_file)
        print("[RESET] pushed_log.json deleted - will push ALL vouchers fresh.\n")

    pushed = set()
    if os.path.exists(log_file):
        with open(log_file, 'r') as f:
            pushed = set(json.load(f))

    # -- Load vouchers ---------------------------------------------------------
    csv_file = os.path.join(os.path.dirname(__file__), 'vouchers_to_create.csv')
    if not os.path.exists(csv_file):
        print("[ERROR] vouchers_to_create.csv not found. Run: node generate_from_frontend.js first.")
        return

    vouchers = []
    with open(csv_file, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for i, row in enumerate(reader):
            # Use VchNo from CSV if present, else generate DEMO-NNNN
            vid = row.get('VchNo', '').strip() or f"DEMO-{i+1:04d}"
            if vid not in pushed:
                row['_VID'] = vid
                vouchers.append(row)

    total = len(vouchers)
    print(f"[INFO] Found {total} new vouchers to push to Tally (company: {COMPANY_NAME})")
    if total == 0:
        print("[DONE] Nothing to push -- all vouchers already in Tally.")
        return

    # -- Push in batches -------------------------------------------------------
    pushed_list = list(pushed)
    success_count = 0

    for i in range(0, total, BATCH_SIZE):
        batch = vouchers[i:i + BATCH_SIZE]
        print(f"\n[BATCH {i//BATCH_SIZE + 1}] Pushing {len(batch)} vouchers...")

        xml_parts = ""
        for v in batch:
            xml_parts += build_voucher_xml(v, v['_VID'])

        envelope = build_envelope(xml_parts)
        res = post_xml(envelope)

        if log_batch_result(i // BATCH_SIZE, res):
            new_ids = [v['_VID'] for v in batch]
            pushed_list.extend(new_ids)
            success_count += len(batch)
            with open(log_file, 'w') as f:
                json.dump(pushed_list, f)
        else:
            print("[STOP] Stopping due to batch error. Partial progress saved.")
            break

    status = "DONE" if success_count == total else "PARTIAL"
    print(f"\n[{status}] {success_count}/{total} vouchers pushed to Tally Wallnut3.")

if __name__ == '__main__':
    run()
