import requests
xml = """<ENVELOPE><HEADER><VERSION>1</VERSION><TALLYREQUEST>Import</TALLYREQUEST><TYPE>Data</TYPE><ID>All Masters</ID></HEADER><BODY><DESC><STATICVARIABLES><SVCURRENTCOMPANY>Wallnut Demo</SVCURRENTCOMPANY></STATICVARIABLES></DESC><DATA><TALLYMESSAGE xmlns:UDF="TallyUDF"><UNIT NAME="Bags" ACTION="Create"><NAME>Bags</NAME><ISSIMPLEUNIT>Yes</ISSIMPLEUNIT></UNIT></TALLYMESSAGE></DATA></BODY></ENVELOPE>"""
print(requests.post('http://localhost:9000', data=xml.encode('utf-8')).text)
