import push_vouchers
xml = """<TALLYMESSAGE xmlns:UDF="TallyUDF">
 <VOUCHER VCHTYPE="Sales" ACTION="Create">
  <DATE>20260401</DATE>
  <VOUCHERTYPENAME>Sales</VOUCHERTYPENAME>
  <VOUCHERNUMBER>DEMO-TEST4</VOUCHERNUMBER>
  <PARTYLEDGERNAME>M/s Shree Cement House</PARTYLEDGERNAME>
  <ALLLEDGERENTRIES.LIST>
   <LEDGERNAME>M/s Shree Cement House</LEDGERNAME>
   <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
   <AMOUNT>-5000</AMOUNT>
  </ALLLEDGERENTRIES.LIST>
  <ALLINVENTORYENTRIES.LIST>
   <STOCKITEMNAME>Wallnut Tile Adhesive (20 Kg)</STOCKITEMNAME>
   <ACTUALQTY>10 Kgs</ACTUALQTY>
   <BILLEDQTY>10 Kgs</BILLEDQTY>
   <RATE>500/Kgs</RATE>
   <AMOUNT>5000</AMOUNT>
   <ACCOUNTINGALLOCATIONS.LIST>
    <LEDGERNAME>Sales Accounts</LEDGERNAME>
    <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
    <AMOUNT>5000</AMOUNT>
   </ACCOUNTINGALLOCATIONS.LIST>
  </ALLINVENTORYENTRIES.LIST>
 </VOUCHER>
</TALLYMESSAGE>"""
envelope = push_vouchers.build_batch_envelope(xml)
print(push_vouchers.post_xml(envelope))
